create table product (
    id varchar(64) primary key,
    article varchar(128) not null,
    article_normalized varchar(128) not null,
    brand varchar(128) not null,
    name varchar(255) not null,
    line_text varchar(255) not null,
    rating double precision not null,
    reviews_count integer not null,
    image varchar(512) not null
);

create table product_badge (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null references product(id) on delete cascade,
    badge varchar(128) not null
);

create table recommended_offer (
    id varchar(64) primary key,
    product_id varchar(64) not null references product(id) on delete cascade,
    title varchar(255) not null,
    price integer not null,
    currency varchar(16) not null,
    delivery varchar(64) not null,
    highlight boolean not null
);

create table product_offer (
    id varchar(64) primary key,
    product_id varchar(64) not null references product(id) on delete cascade,
    supplier varchar(255) not null,
    price integer not null,
    stock_text varchar(64) not null,
    city varchar(64) not null
);

create table product_analog (
    id varchar(64) primary key,
    product_id varchar(64) not null references product(id) on delete cascade,
    brand varchar(128) not null,
    article varchar(128) not null,
    name varchar(255) not null
);

create table analog_offer (
    id bigint generated by default as identity primary key,
    analog_id varchar(64) not null references product_analog(id) on delete cascade,
    supplier varchar(255) not null,
    price integer not null
);

create table garage_car (
    id varchar(64) primary key,
    label varchar(255) not null,
    subtitle varchar(255) not null,
    vin varchar(32) not null,
    catalog_hint varchar(255) not null
);

create table catalog_group (
    id varchar(64) primary key,
    title varchar(255) not null,
    count_text varchar(32) not null
);

create table vehicle_lookup (
    vin varchar(32) primary key,
    brand varchar(128) not null,
    model varchar(128) not null,
    generation varchar(128) not null,
    model_year varchar(16) not null,
    engine varchar(128) not null
);
